### ISSUE TITLE
Is there and way using which I can track only given paths?

### ISSUE THREAD

**Issue by rkisdp** [django-request/django-request#253] opened 2022-07-05 19:59 UTC
I'm looking for any way to track only specific paths whichever I want to track?
I mean something opposite of REQUEST_IGNORE_PATHS feature

**Comment by felixxm** [comment] 2023-01-10 16:03
Marking as a duplicate of #212 which will allow filtering specific paths.

**Closed by felixxm** 2023-01-10 16:03 UTC
