### ISSUE TITLE
Support for CloudFlare reverse proxy (real IP of client)

### ISSUE THREAD

**Issue by iamnotagentleman** [django-request/django-request#222] opened 2021-03-26 21:51 UTC
Hi, when we use django with cloudflare reverse proxy, REMOTE_ADDR does not giving real IP of client (gives IP of proxy) should get from HTTP_CF_CONNECTING_IP header.

**Comment by christianwgd** [comment] 2021-08-01 16:02
Hi, stumbled over this problem too and solved it by subclassing the django-request middleware to update the REMOTE_ADDR request header. You can find the middleware file here: https://gist.github.com/christianwgd/2b46cf6748d137b1e3ca000eb83678b3

In default its configured for an apache proxy server but you can add a setting to adopt your case:
REQUEST_FORWARDED_ADDR_FIELD = 'HTTP_CF_CONNECTING_IP'

**Comment by felixxm** [comment] 2023-03-07 19:20
Duplicate of #54.

**Closed by felixxm** 2023-03-07 19:20 UTC
