### ISSUE TITLE
Doesn't work in production enironment

### ISSUE THREAD

**Issue by kabaltech** [django-request/django-request#262] opened 2023-02-27 23:11 UTC
Noticed this isn't working in production environment, with Gunicorn. Actually it's not picking up the Middleware code. I know this, because I wrote a custom middleware extending Request middle and it isn't picking up in production but works fine in Dev.

Any reason why this might be so? And yes the Ordering is fine, it's After Auth middleware.

**Comment by ramiboutas** [comment] 2023-03-01 18:19
It is not working for me either https://github.com/ramiboutas/englishquiz/issues/9

I disabled caching for some time (just it was the problem), but it didn't bring anything

@felixxm @kylef What can we check? 

Thank you!

**Comment by hvitis** [comment] 2023-03-06 22:29
IP Forwarding? I switched mine some time ago, but when it was not working when used, port and IP forwarding was an issue in my case.

**Comment by felixxm** [comment] 2023-03-07 19:20
Duplicate of #54.

**Closed by felixxm** 2023-03-07 19:20 UTC
Labels: duplicate
